### ISSUE TITLE
Installed version doesn't have access to build setting preset files

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/XcodeGen#31]
This results in projects that don't have default build settings applied for config type, platform or product type

**Comment by yonaskolb** [comment]
@pepibumur Do you have any tips here regarding homebrew? We need the `SettingsPreset` folder to be somehow accessible when running

**Comment by yonaskolb** [comment]
I've managed to add that directory in by adding this to the install script in the Formula
```
pkgshare.install "SettingPresets"
```
Now I need find to out how to access these files

**Comment by yonaskolb** [comment]
Fixed. Awaiting new release

**Comment by pepibumur** [comment]
I just saw it. How did you manage to access the files @yonaskolb?

**Comment by yonaskolb** [comment]
```
Path(Bundle.main.bundlePath) + "../share/xcodegen/SettingPresets/\(path).yml"
```
If that doesn't exist I check the following for local builds and tests
```
Path(#file).parent().parent().parent() + "SettingPresets/\(path).yml"
```

**Comment by farshadtx** [comment]
It looks this issue is still happening, Installed latest version(2.17.0) by `mint`.

**Comment by yonaskolb** [comment]
@farshadtx so the setting presets aren't loading? Do you get warnings when generating?

**Comment by farshadtx** [comment]
Yes, that's the problem.
